name: helpdesk_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http : ^1.2.1
  google_fonts: ^6.2.1
  floor: ^1.4.2
  provider: ^6.1.2
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  flutter_barcode_scanner: ^2.0.0
  google_sign_in: ^5.4.2
  async: ^2.11.0
  simple_animations: ^5.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
  assets : 
  - assets/icona_scuola.png
  - assets/appbar.png
